default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: secret

development:
  <<: *default
  database: hello_world_development

test:
  <<: *default
  database: hello_world_test

production:
  <<: *default
  database: hello_world_production
  password: <%= ENV["DB_PASSWORD"] %>
